name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on: [push, pull_request]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  BuildAndTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth 1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Run tests
        run: bun run test
